version: "3"
services:
  react-app:
    container_name: ht-react
    build: 
      context: ./frontend
      dockerfile: ./docker/DockerFile
    stdin_open: true
    ports:
      - "3000:3000"
    depends_on: 
      - api-server
    restart: always

  api-server:
    container_name: ht-express
    build: 
      context: ./backend
      dockerfile: ./docker/DockerFile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    restart: always

  mongo:
    container_name: ht-mongo
    image: mongo
    ports:
    - "27017:27017"
    volumes:
      - ./data/db:/data/db
    restart: always

# persists data after container exits
volumes:
  mongo-data:
    driver: local