version: "3"
services:
  react-app:
    image: react-app
    # Keeps react container live after startup
    stdin_open: : true
    ports:
      - "3000:3000"
    networks: 
      - habit-tracker-app

  api-server:
    image: api-server
    ports:
      - "8080:8080"
    networks: 
      - habit-tracker-app
    # Ensures containers start in the right order (mongo starts before express so express can connect to it)
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
    - "27017:27017"
    networks: 
      - habit-tracker-app
    volumes:
      - mongo-data:/data/db

# by explicitly defining network, we isolate this app(s) from other containers that are on the default docker network
networks: 
  habit-tracker-app:
    drive: bridge

# persists data after container exits
volumes:
  mongo-data:
    driver: local