version: "3"
services:
  mongodb:
    build:
      context: ./data
      dockerfile: ./Dockerfile
    container_name: mongodb
    environment:
    - PUID=1000
    - PGID=1000
    volumes:
    - ./data/db:/data/mongodb
    ports:
    - 27017:27017
    restart: unless-stopped

# persists data after container exits
volumes:
  mongo-data:
    driver: local