version: "3"
services:
  react-app:
    container_name: ht-react
    build: 
      context: ./frontend
      dockerfile: Dockerfile
    stdin_open: true
    ports:
      - 3000:3000
    depends_on: 
      - api-server
    restart: always

  api-server:
    container_name: ht-express
    build: 
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    restart: always
    depends_on: 
      - mongo

  mongo:
    container_name: ht-mongo
    build:
      context: ./data
      dockerfile: ./Dockerfile
    environment:
      - PUID=1000
      - PGID=1000
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/mongodb
    restart: unless-stopped