# sets base image for subsequent instructions
# Here we import node image into container which gives us everything we need to build this express app
FROM node

# Instructs Docker to use this path as the default location for all subsequent commands
WORKDIR /server

# Copies the package.json files from local directory, into container's /app/ directory
COPY package*.json ./

# Install dependencies defined in package.json
# Production, replace with:
# RUN npm ci --only=production
RUN npm install

# Copy local server files into the image
COPY . /server

# Expose port for app to bind to
EXPOSE 5000

# Starts server.js (node server.js)
CMD ["npm", "start"]
